name:                jstris-ai
version:             0.1.0.0
github:              "jbrot/jstris-ai"
license:             GPL-3
author:              "Joshua Brot"
maintainer:          "jbrot@umich.edu"
copyright:           "2019(c) Joshua Brot"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jbrot/jstris-ai#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- containers
- finitary-derive
- logict
- MonadRandom
- mtl
- random
- random-shuffle
- text
- transformers
- vector
- webdriver

library:
  source-dirs: src

executables:
  jstris-ai-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jstris-ai
